
name: build workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    
    - name: install net8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: restore
      run: dotnet restore

    - name: build and test
      run: |
        dotnet build --no-restore --configuration release
        dotnet test --no-build --no-restore --verbosity normal
