name: pack worklfow

on:
  push:
    tags:
      - '*.*.*'

env:
  packageIdd: EventStorage.Workflows

jobs:
  pack:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      
    - name: install net8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: build
      run: dotnet build --configuration release

    - id: get-version
      name: get-tag
      run: |
        vtag=${{ github.ref_name }}; tag=${vtag#v}; echo "tag=$tag" >> $GITHUB_OUTPUT

    - name: pack
      run: >
        dotnet pack --no-build --no-restore --configuration release -p:PackageId=${{ env.packageIdd }}
        -p:PackageVersion=${{ steps.get-version.outputs.tag }} --output .

    # - name: github push
    #   run: >
    #     dotnet nuget push ${{ env.packageIdd }}.${{ steps.get-version.outputs.tag }}.nupkg
    #     -k ${{ secrets.GITHUB_TOKEN }} -s "github"

    - name: nuget push
      run: >
        dotnet nuget push ${{ env.packageIdd }}.${{ steps.get-version.outputs.tag }}.nupkg
        -k ${{ secrets.NUGETAPIKEY }} -s nuget
