name: pack worklfow

on:
  push:
    tags:
      - '*.*.*'

env:
  packageIdd: EventStorage.Workflows
  github_url: https://nuget.pkg.github.com/eventsourcer/index.json
  nuget_url: https://api.nuget.org/v3/index.json

jobs:
  pack:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      
    - name: install net8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: get version
      id: get-version
      run: |
        vtag=${{ github.ref_name }}; tag=${vtag#v}; echo "tag=$tag" >> $GITHUB_OUTPUT

    - name: build
      run: dotnet build --configuration release

    - name: pack
      run: >
        dotnet pack -c release -p:PackageId=${{ env.packageIdd }}
        -p:PackageVersion=${{ steps.get-version.outputs.tag }} -o .

    - name: github auth
      run: >
        dotnet nuget add source --username eventsourcer --password ${{ secrets.GITHUB_TOKEN }}
        --store-password-in-clear-text --name gh ${{ env.github_url }}
    
    - name: list sources
      run: dotnet nuget list source
      
    - name: nuget auth
      run: >
        dotnet nuget add source --username eventstorage --password ${{ secrets.NugetApikey }}
        --store-password-in-clear-text --name nuget_source ${{ env.nuget_url }}

    - name: github push
      run: dotnet nuget push *.nupkg -s gh --skip-duplicate

    - name: nuget push
      run: dotnet nuget push *.nupkg -s nuget_source --skip-duplicate
